Traceback (most recent call last):
  File "/Users/mriki/workspace/jupyterbook/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mriki/workspace/jupyterbook/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mriki/workspace/jupyterbook/.venv/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/mriki/.rye/py/cpython@3.8.18/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/mriki/workspace/jupyterbook/.venv/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/mriki/workspace/jupyterbook/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mriki/workspace/jupyterbook/.venv/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd 
df = pd.DataFrame(
    [[160,140,180,170,165],
    [60,50,72,64,80],
    ["女","女","男","男","男"],
    ],
    columns="A子、B美、C太、D介、E吉".split("、")
).T
df.columns = ["身長","体重","性別"]
df
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m 
[1;32m      2[0m df [38;5;241m=[39m pd[38;5;241m.[39mDataFrame(
[1;32m      3[0m     [[[38;5;241m160[39m,[38;5;241m140[39m,[38;5;241m180[39m,[38;5;241m170[39m,[38;5;241m165[39m],
[1;32m      4[0m     [[38;5;241m60[39m,[38;5;241m50[39m,[38;5;241m72[39m,[38;5;241m64[39m,[38;5;241m80[39m],
[0;32m   (...)[0m
[1;32m      7[0m     columns[38;5;241m=[39m[38;5;124m"[39m[38;5;124mA子、B美、C太、D介、E吉[39m[38;5;124m"[39m[38;5;241m.[39msplit([38;5;124m"[39m[38;5;124m、[39m[38;5;124m"[39m)
[1;32m      8[0m )[38;5;241m.[39mT
[1;32m      9[0m df[38;5;241m.[39mcolumns [38;5;241m=[39m [[38;5;124m"[39m[38;5;124m身長[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124m体重[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124m性別[39m[38;5;124m"[39m]

[0;31mModuleNotFoundError[0m: No module named 'pandas'

